id: implement_get_planets
learningObjectives:
  - Master data querying and filtering using Ditto's collection API
hints:
  - Look at the DittoServiceImp class in the com.ditto.guides.services package
  - The getPlanets method should query non-archived planets and order them by distance from the sun
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: I've prepared a `DittoServiceImp` class with all the necessary methods we'll need.
              Let's implement them one by one, starting with the `getPlanets` flow.
          - text: Take a look at the DittoServiceImp class in the services package. You'll see
              that it already has the structure set up, including comments explaining what
              each method should do. Let's focus on implementing the getPlanets method first.
          - text: Once you've implemented getPlanets, create a pull request so we can check
              your implementation before moving on to the other methods. Remember, we want
              to query only non-archived planets and order them by their distance from the sun.
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    do:
      - actionId: github_pr_review
        params:
          messages:
            person: lucca
