id: handling_data_operations
learningObjectives:
  - Implement data fetch and save operations in DittoServiceImp.
hints:
  - Use Ditto's sync API to fetch data from MongoDB.
  - Implement additional methods to persist new data back to your database via
    Ditto.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Ah, new day, new beginnings. Let’s handle some data operations today using
              the power of Ditto. Your task, should you choose to accept it (or
              comply based on Ness's request), is to implement data fetching and
              saving operations. Everything should be seamless between your
              Android app and that trusty MongoDB.
          - text: Trust your instincts and think of it as a digital synapse firing with
              flawless execution.
    - actionId: ready_message
      params:
        person: lucca
trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: finish_step
