id: data_collision_resolution
learningObjectives:
  - Implement logic for resolving data conflicts in DittoServiceImp.
hints:
  - Check Ditto’s conflict resolution mechanisms in their reference guide.
  - Consider leaning on timestamps or 'last writer wins' strategy.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: You're doing amazing. Now, have you ever played a game of Tetris? Consider
              this step something similar, where you'll have to resolve data
              collisions carefully and precisely. Implement logic within
              DittoServiceImp to handle possible data conflicts.
          - text: "Remember the ancient wisdom: Clashing data, though inevitable, makes one
              a better developer."
    - actionId: ready_message
      params:
        person: lucca
trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: finish_step
